-- MySQL Script generated by MySQL Workbench
-- Model: E-Commerce    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP DATABASE IF EXISTS ECOMMERCE;
CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;

-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `First Name` VARCHAR(45) NOT NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `EmailID` INT NOT NULL,
  `Phone Number` INT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`) );


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Employee` (
  `EmployeeID` INT NOT NULL AUTO_INCREMENT,
  `SupervisorID` INT NULL,
  `Role` VARCHAR(45) NULL,
  `Date Joined` DATE NULL,
  PRIMARY KEY (`EmployeeID`) );


-- -----------------------------------------------------
-- Table `Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `Seller` VARCHAR(45) NULL,
  `Price` DECIMAL NULL,
  `Item Name` VARCHAR(45) NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`ItemID`) );


-- -----------------------------------------------------
-- Table `Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Item` (
  `ArticleID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Price` DECIMAL NOT NULL,
  `Seller` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ArticleID`));


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payment` (
  `Card Number` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Expiration Date` INT NOT NULL,
  PRIMARY KEY (`Card Number`) );


-- -----------------------------------------------------
-- Table `Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reviews` (
  `ReviewID` INT NOT NULL AUTO_INCREMENT,
  `SellerID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `Detailed Review` VARCHAR(45) NOT NULL,
  `ArticleID` INT NOT NULL,
  `Ratings` FLOAT NULL,
  PRIMARY KEY (`ReviewID`));

-- -----------------------------------------------------
-- Table `Shipment/Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShipmentDelivery` (
  `Tracking #` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Details` VARCHAR(45) NULL,
  `Charge` DECIMAL NOT NULL,
  PRIMARY KEY (`Tracking #`) );


-- -----------------------------------------------------
-- Table `Shopping Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoppingCart` (
    `CartID` INT NOT NULL AUTO_INCREMENT,
    `Price per item` DECIMAL NULL,
    `Total` DECIMAL NULL,
    `Items` VARCHAR(45) NULL,
    `Quantity` INT NULL,
    PRIMARY KEY (`CartID`) ); 
    
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
